Puppet
odia/buenosairescompras pull request #5
Opened 2022-01-28 23:48 UTC by xaiki

rewrite parsing bac.gob with puppet.

2022-01-29 06:29 UTC, seppo0010 requested changes
I would like you to use a different repo as it looks like a different project than what currently exists

2022-01-29 06:29 UTC, seppo0010 commented on puppet/Dockerfile
> +    MAINTAINER Niv Sardi <x@filtra.me>
is there any reason for the indentation? I don't think I've seen it in Dockerfiles 🤔

2022-01-29 06:29 UTC, seppo0010 commented on puppet/Dockerfile
> +RUN yarn
I think you can run yarn before copying src to have node_modules cache when you change src

2022-01-29 13:43 UTC, xaiki commented on puppet/Dockerfile
> +    MAINTAINER Niv Sardi <x@filtra.me>
emacs thought it was sexeh, fixed.

2022-01-29 13:44 UTC, xaiki commented on puppet/Dockerfile
> +RUN yarn
fixd in 79a93b6

2022-01-29 13:46 UTC, xaiki commented
about the different repo:
the plan is to merge and compare the data from the csv/api/datos abiertos to the scrapped one, it doesn't make sense to me to move it out as we'll need to merge it back in soon enough. we even have an issue for this here https://github.com/odia/buenosairescompras/issues/3


rationale: it's the same data, it should be in the same repo…

2022-01-29 13:46 UTC, xaiki commented on puppet/Dockerfile
> +    MAINTAINER Niv Sardi <x@filtra.me>
ab7ee13

2022-02-15 15:36 UTC, xaiki commented
Fixes #3

2022-02-15 15:36 UTC, merged